### ISSUE TITLE
Releasing to Maven Central

### ISSUE THREAD

**Issue by tonydamage** [tunguski/msb3-maven-skin#1]
Hi,
your maven skin site seems useful, are you planning to release it to maven central in foreseeable future?

I am working on project, where we can not consume external SNAPSHOT version and having release version would be helpful.

**Comment by jaafar-bennani-smires** [comment]
Hi,
Happy to see this work can be helpfull.
I have been quite busy last 2 months to work on this, so i had not planned to release it to central repo for the moment.
Additionnaly, i was more thinking about releasing it to my own public repo (easier for me to manage currently).
I can package you a released version quite soon and then i can contact you while my release process will be stable?

**Comment by tonydamage** [comment]
I can easily create release version myself, but that will not help, since I
can only consume artefacts published in central.

Actually it does not hurry now, just trying to figure out when I can
incorporate bootsrap3 based maven sites to our projects.
Dňa 3.6.2015 11:30 používateľ "Jaafar BENNANI-SMIRES" <
notifications@github.com> napísal:

**Comment by jaafar-bennani-smires** [comment]
Well i understand :-). Not easy to get a stable maven bootsrap3 skin...
I'll keep you informed as soon as i'll release it properly (in next 2-3 weeks i think - my process affects more than this single artifact) and i'll keep in mind to deploy a stable version in the central repo.

**Comment by tonydamage** [comment]
Thanks :)
Dňa 3.6.2015 11:41 používateľ "Jaafar BENNANI-SMIRES" <
notifications@github.com> napísal:

**Comment by jaafar-bennani-smires** [comment]
Oups, i thinks i answer for tunguski who is the owner of msb3-maven-skin repo.
My fork is https://github.com/tawja/twj-maven-skin and i have not created a puch request for the moment.
Sorry.

**Comment by tunguski** [comment]
Hi Tony & Jaafar :)
It was really interesting to read answers from Jaafar in this project! :) I'm very happy that this work is valuable for you both!

Tony, it's not a problem to release this project. I made it for my internal purposes, so I've tested the version that you see on the demo site. If you want to use some custom settings, please generate your site and check if everything looks ok. Issue problems if you find any.

I'll check what is the deploy workflow is and make a stable release soon.

**Comment by tunguski** [comment]
I've released version 0.1.0 to maven central. Beside upgrades:
- boostrap to 3.3.6
- highlight.js to 9.0.0

things did not change.
